AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The keys for encrypting application secrets in each environment.

Parameters:
  Environment:
    Description: The environment type
    Type: String
    Default: local
    AllowedValues:
      - "local"
      - "development"
      - "build"
      - "staging"
      - "integration"
      - "production"
  LocalName:
    Description: Unique name used for ephemeral environments
    Type: String
    Default: ""
  Application:
    Description: "The application that the waf should protect."
    Type: "String"
    MaxLength : 22
    AllowedPattern: "^[a-zA-Z0-9-]+$"

Rules:
  LocalNameRequiredForLocalEnvironment:
    RuleCondition: !Equals [ !Ref Environment, "local" ]
    Assertions:
      - Assert: !Not [ !Equals [ !Ref LocalName, "" ] ]
        AssertDescription: >
          Must specify LocalName when Environment is "local"
  LocalNameEmptyForNotLocalEnvironment:
    RuleCondition: !Not [ !Equals [ !Ref Environment, "local" ] ]
    Assertions:
      - Assert: !Equals [ !Ref LocalName, "" ]
        AssertDescription: >
          Must not specify LocalName when Environment is not "local"  

Outputs:
  SecretsKmsKeyArn:
    Description: "ARN of the KMS key that should be used to encrypt secrets for this application."
    Value: !GetAtt SecretsKmsKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-secrets-kms-key"

Resources:
  SecretsKmsKeyArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Application}/${Environment}${LocalName}/secrets-kms-key"
      Type: String
      Value: !GetAtt SecretsKmsKey.Arn

  SecretsKmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: Key for encrypting secrets for this configuration set
      Enabled: TRUE
      EnableKeyRotation: TRUE
      Tags:
        - Key: "sse:application"
          Value: !Ref Application
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action: kms:*
            Resource: "*"
          - Sid: Enable applications to decrypt
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "kms:Decrypt"
              - "kms:DescribeKey"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Ref AWS::AccountId
                "kms:ViaService": !Sub "secretsmanager.${AWS::Region}.amazonaws.com"
              StringLike:
                "kms:EncryptionContext:SecretARN": !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${Application}/*"

  SecretsKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${Application}/${Environment}${LocalName}-secrets-key"
      TargetKeyId: !Ref SecretsKmsKey
