AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment pipelines for the Product Pages

Parameters:
  # Template reference https://github.com/govuk-one-login/devplatform-deploy
  TemplateStorageBucket:
    Type: String
    Default: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com
  ExportNamePrefix:
    Type: String
    Default: secure-pipelines
    AllowedPattern: ^.*[^-]$
    Description: Prefix to use when importing or exporting values
  StackNamePrefix:
    Type: String
    Default: productpages
    AllowedPattern: ^.*[^-]$
    MaxLength: 14
    Description: Prefix applied to the deployed application stack names
  Environment:
    Type: String
  NextAccount:
    Type: String
    Default: ""
  GitHubRepositoryName:
    Type: String
    Default: none
  OneLoginRepositoryName:
    Type: String
    Default: onboarding-product-page
  SigningProfileARN:
    Type: String
  SigningProfileVersionARN:
    Type: String
  ContainerSigningKeyARN:
    Type: String
    Default: none
  ProductPagesFrontendSourceBucketARN:
    Type: String
    Default: none
  ProductPagesFrontendArtifactSourceBucketEventTriggerRoleArn:
    Type: String
    Default: none

Conditions:
  IsFinalAccount: !Not [ !Condition PromotionEnabled ]
  PromotionEnabled: !Not [ !Equals [ !Ref NextAccount, "" ] ]
  ProductPagesProductPagesFrontendRepositorySource: !Equals [ !Ref FrontendSourceBucketARN, "none" ]

Resources:
  ProductPagesFrontendDeployer:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBDeployer
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Frontend
        - Key: sse:deployment-source
          Value: secure-pipelines
      Parameters:
        Environment: !Ref Environment
        SAMStackName: !Sub ${StackNamePrefix}-frontend
        TruncatedPipelineStackName: !Sub ${StackNamePrefix}-frontend
        ContainerSignerKmsKeyArn: !Ref ContainerSigningKeyARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        SigningProfileArn: !Ref SigningProfileARN
        VpcStackName: !ImportValue VPC-StackName
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !If [ IsFinalAccount, All, Failures ]
        ArtifactSourceBucketArn: !Ref ProductPagesFrontendSourceBucketARN
        ArtifactSourceBucketEventTriggerRoleArn: !Ref ProductPagesFrontendArtifactSourceBucketEventTriggerRoleArn
        GitHubRepositoryName: !If [ ProductPagesFrontendRepositorySource, !Ref GitHubRepositoryName, "none" ]
        OneLoginRepositoryName: !If [ ProductPagesFrontendRepositorySource, !Ref OneLoginRepositoryName, "none" ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        PipelineEnvironmentNameEnabled: "Yes"
        AllowedServiceOne: ECR & ECS

  ProductPagesFrontendECRRepository:
    Type: AWS::CloudFormation::Stack
    Condition: ProductPagesFrontendRepositorySource
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/container-image-repository/template.yaml
      Parameters:
        PipelineStackName: !Select [ 1, !Split [ "/", !Ref ProductPagesFrontendDeployer ] ]

  ProductPagesFrontendTestImagesRepository:
    Type: AWS::CloudFormation::Stack
    Condition: ProductPagesFrontendRepositorySource
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/test-image-repository/template.yaml
      Parameters:
        PipelineStackName: !Select [ 1, !Split [ "/", !Ref ProductPagesFrontendDeployer ] ]
        RetainedImageCount: "25"

  ProductPagesFrontendDeploymentPolicy:
    Type: AWS::IAM::Policy
    Condition: ProductPagesFrontendRepositorySource
    Properties:
      Roles: [ !GetAtt ProductPagesFrontendDeployer.Outputs.GitHubActionsRoleName ]
      PolicyName: !Sub ${StackNamePrefix}-productpages-frontend-deployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:ListPipelineExecutions
              - codepipeline:StartPipelineExecution
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${FrontendDeployer.Outputs.PipelineName}
          - Effect: Allow
            Action: ecr:BatchDeleteImage
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ProductPagesFrontendECRRepository.Outputs.ContainerRepositoryName}

Outputs:
  # Promotion
  ProducePagesFrontendPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt FrontendDeployer.Outputs.ArtifactPromotionBucketArn
  ProducePagesFrontendPromotionBucketEventTriggerRoleArn:
    Condition: PromotionEnabled
    Value: !GetAtt FrontendDeployer.Outputs.ArtifactPromotionBucketEventTriggerRoleArn

  # Deployment
  ProducePagesFrontendDeploymentRoleArn:
    Condition: ProductPagesFrontendRepositorySource
    Value: !GetAtt FrontendDeployer.Outputs.GitHubActionsRoleArn
  ProducePagesFrontendArtifactSourceBucketName:
    Condition: ProductPagesFrontendRepositorySource
    Value: !GetAtt FrontendDeployer.Outputs.GitHubArtifactSourceBucketName
  ProducePagesFrontendECRRepositoryName:
    Condition: ProductPagesFrontendRepositorySource
    Value: !GetAtt FrontendECRRepository.Outputs.ContainerRepositoryName
  ProducePagesFrontendTestECRRepositoryName:
    Condition: ProductPagesFrontendRepositorySource
    Value: !GetAtt FrontendECRRepository.Outputs.ContainerRepositoryName
  ProducePagesFrontendPipelineName:
    Value: !GetAtt FrontendDeployer.Outputs.PipelineName
