name: Monitoring smoke tests deployment

on:
  push:
    branches:
      - main
    paths:
      - monitoring/smoke-tests/*

permissions: { }

defaults:
  run:
    shell: bash
    working-directory: ./monitoring/smoke-tests

env:
  STACK_NAME: sse-infra-monitoring-smoke-tests

jobs:
  build:
    name: Build smoke tests stack
    runs-on: ubuntu-latest

    steps:
      - name: Build smoke test stack
        uses: govuk-one-login/github-actions/sam/build-application@6144f39407b01c9b25b39537b3956deca9e32620 # 22/02/2024
        id: build-smoke-stack
        with:
          pull-repository: true
          template: monitoring/smoke-tests/smoke-tests.template.yml
          manifest: monitoring/smoke-tests/src/package.json
          cache-name: ${{ vars.STACK_NAME }}
          artifact-name: ${{ vars.STACK_NAME }}-sam

      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@6144f39407b01c9b25b39537b3956deca9e32620 # 22/02/2024
        id: deploy-smoke-stack
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          artifact-name: ${{ steps.build-smoke-stack.outputs.artifact-name }}
          template: monitoring/smoke-tests/smoke-tests.template.yml
          s3-prefix: sse-preview
          tags: |-
            sse:component=${{ vars.STACK_NAME }}
            sse:stack-type=infrastructure
            sse:deployment-source=github-actions

      - name: Build stack
        uses: govuk-one-login/github-actions/sam/build-application@6144f39407b01c9b25b39537b3956deca9e32620 # 22/02/2024
        id: build-canary-stack
        with:
          pull-repository: true
          template: monitoring/smoke-tests/canary-alarms.template.yml
          cache-name: ${{ vars.STACK_NAME }}
          artifact-name: ${{ vars.STACK_NAME }}-sam

      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@6144f39407b01c9b25b39537b3956deca9e32620 # 22/02/2024
        id: deploy-canary-stack
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          artifact-name: ${{ steps.build-canary-stack.outputs.artifact-name }}
          template: monitoring/smoke-tests/canary-alarms.template.yml
          s3-prefix: sse-preview
          tags: |-
            sse:component=${{ vars.STACK_NAME }}
            sse:stack-type=infrastructure
            sse:deployment-source=github-actions
          parameters: |-
            EnableAlerting=true
            SmokeStack=${{ steps.deploy-smoke-stack.outputs.stack-name }}